source 'https://rubygems.org'

ruby '2.4.0'

gem 'rails', '4.2.1'
gem 'airbrake', '~> 4.0.0'
gem 'pg'
gem 'jquery-rails'
gem 'jquery-ui-rails'
gem 'jbuilder', '~> 2.0'
gem 'haml-rails'
gem 'enumerize'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '~> 3.2.0'
gem 'execjs'
gem 'therubyracer', '~> 0.12.3', platforms: :ruby
gem 'coffee-rails', '~> 4.1.0'
gem 'libv8', '~> 3.16.14'
gem 'authority'
gem 'bcrypt', '~> 3.1.11'
gem 'active_form', github: 'rails/actionform', ref: '41ec958'
gem 'simple_form'
gem 'bootstrap-sass'
gem 'bootstrap_glyphicons-rails'
gem 'state_machine', github: 'seuros/state_machine'
gem 'draper'
gem 'russian'
gem 'russian_sex'
gem 'carrierwave'
gem 'mini_magick'
gem 'rmagick', '2.15.3'
#gem 'datetimepicker-rails', github: 'zpaulovics/datetimepicker-rails', submodules: true
gem 'js-routes'
gem 'i18n-js', github: 'fnando/i18n-js'
gem 'omniauth-google-oauth2'
gem 'omniauth-vkontakte'
gem 'omniauth-twitter', '~> 1.4'
gem 'omniauth-facebook', '4.0.0'
gem 'momentjs-rails', '>= 2.9',  github: 'derekprior/momentjs-rails'
gem 'awesome_print'
gem 'ckeditor', github: 'galetahub/ckeditor'
gem 'configus'
gem 'foursquare2', github: 'nitinstp23/foursquare2', branch: :gemspec_fix
gem 'validates'
gem 'font-awesome-rails', '4.7.0.1'
gem 'sidekiq', '4.2.10'
gem 'foundation-rails', '5.5.2.1'
gem "autoprefixer-rails"
gem 'select2-rails'
gem 'jasny_bootstrap_extension_rails'
gem 'sinatra', '>= 1.3.0', require: nil
gem 'kaminari'
gem 'bootstrap-kaminari-views'
gem 'russia_regions', '>= 0.0.4'
gem 'github_api'
gem 'pg_search'
gem 'reform'
gem 'rails_email_preview', '~> 0.2.29'
#gem 'scopes_rails', '>= 0.0.3'
gem 'scopes_rails', github: 'kalashnikovisme/scopes_rails', branch: 'list_of_scopes'
gem 'trap', '~> 1'
gem 'more_html_tags'
gem 'hashdiff'
gem 'react_webpack_rails'
gem 'rwr-redux'
gem 'virtus'
gem 'karamzin'
gem 'responders', '~> 2.0'
gem 'kabal', '>= 1.3'
gem 'youtube_rails', github: 'luizpicolo/youtube_rails'
gem 'unicorn-rails'
gem 'xls_exporter'
gem 'youtube_addy'
gem 'json', '~> 1.8.6' 
gem 'sprockets', '>= 3.7.1'
gem 'builder', '>= 3.2.3'
gem 'thread_safe', '>= 0.3.6'

group :development, :test do
  gem 'byebug'
  gem 'web-console', '2.0.0.beta2'
  gem 'spring', '1.3.4'
  gem 'factory_girl_rails'
  gem 'quiet_assets'
  gem 'colorize', '0.6.0'
  gem 'better_errors'
  gem 'railroady'
  gem 'pry'
end

group :test do
  gem 'simplecov', '>= 0.14.1', require: false
  gem 'tconsole-rails4'
  gem 'coveralls', '>= 0.8.20', require: false
  gem 'webmock'
end
